update

diff --git a/dayfetch b/dayfetch
--- a/dayfetch
+++ b/dayfetch
@@ -1,104 +1,125 @@
-#!/usr/bin/env bash
+#!/usr/bin/env sh
 
 animation="skull"
 
 delay=0.5
 
-printf -v c0 "\033[0m"
-printf -v c1 "\033[31m"
-printf -v h1 "\033[1;31m"
+c0=$(echo -e "\e[0m")
+c1=$(echo -e "\e[31m")
+h1=$(echo -e "\e[1;31m")
 
-while getopts ":hp:a:d:c:" option; do
-    case $option in
-        h ) echo "dayfetch: animated system info fetch"
-            echo "usage: dayfetch [options]"
-            echo "-h display this help message"
-            echo "-p path to animations (skull)"
-            echo "-a animation (skull, moon, face, bunny)"
-            echo "-d delay between frames (float)"
-            echo "-c color (31-37)"
-            exit
-            ;;
-        p ) animations=$OPTARG ;;
-        a ) animation=$OPTARG ;;
-        d ) delay=$OPTARG ;;
-        c ) printf -v c1 "\033[${OPTARG}m"
-            printf -v h1 "\033[1;${OPTARG}m"
-            ;;
-    esac
-done
+info=()
 
-if [ -n "$animations" ] && [ -d $animations/$animaion ]; then
-    path=$animations/$animation
-elif [ -d ~/.local/share/dayfetch/$animation ]; then
-    path=~/.local/share/dayfetch/$animation
-elif [ -d /usr/share/dayfetch/$animation ]; then
-    path=/usr/share/dayfetch/$animation
-else
-    echo "Animation not found"
-    exit
-fi
-
-
-whoami=$(whoami)
-hostname=$(hostname)
-
-if test -f /etc/os-release
-then
-    source /etc/os-release
-    os=$PRETTY_NAME
-elif command -v lsb_release &> /dev/null
-then
-    os=$(lsb_release -sd | tr -d '"')
-fi
-
-kernel=$(uname -r)
-
-init=$(basename $(readlink /sbin/init))
-if [ -z "$init" ]; then
-	init=$(/sbin/init --version | awk 'NR==1 { print $1 }')
-fi
-
-shell=$(basename $SHELL)
-
-uptime=$(uptime -p | cut -b 4-)
-
-fetch=(
-    "$h1$whoami$c0@$h1$hostname$c0"
-    "${h1}os${c0} $os"
-	"${h1}kernel${c0} $kernel"
-	"${h1}init${c0} $init"
-    "${h1}shell${c0} $shell"
-    "${h1}uptime${c0} $uptime"
-)
-
-entries=${#fetch[@]}
-
-cleanup () {
-    clear
-    printf "\e[?25h"
+input() {
+	while getopts "ha:d:c:" option; do
+		case ${option} in
+			h ) echo "dayfetch: animated system info fetch"
+				echo "usage: dayfetch [options]"
+				echo "-h display this help message"
+				echo "-a animation (skull, moon, face, bunny, earth)"
+				echo "-f fps"
+				echo "-c color (1-7)"
+				exit
+				;;
+			a ) animation=${OPTARG} ;;
+			d ) delay=$((1 / ${OPTARG})) ;;
+			c ) c1=$(echo -e "\e[3${OPTARG}m")
+				h1=$(echo -e "\e[1;3${OPTARG}m")
+				;;
+		esac
+	done
 }
 
-trap cleanup EXIT
-trap 'clear' SIGWINCH
-printf "\e[?25l"
-clear
+check() {
+	if [ -d ~/.local/share/dayfetch/$animation ]; then
+		path=~/.local/share/dayfetch/$animation
+	elif [ -d animations/$animation ]; then
+		path=animations/$animation
+	else
+		echo "Animation not found"
+		exit
+	fi
+}
 
-while true; do
-    for frame in $(ls $path | sort -g); do
-        printf "\033[H"
+fetch() {	
+	username=${USER:-$(id -un)}
+	hostname=${HOSTNAME:-$(hostname)}
+	if [ -f /etc/os-release ]
+	then
+		source /etc/os-release
+	fi
+	os=${PRETTY_NAME:-$(lsb_release -sd | tr -d '"')}
+	kernel=$(uname -r)
+	shell=${SHELL##*/}
+	uptime=$(uptime -p)
+	uptime=${uptime#* }
 
-        entry=0
-        while IFS= read -r line; do
-            line=$(echo "$line" | sed "s/{c1}/$c1/g;s/{c0}/$c0/g")
-            if [ $entry -lt $entries ]; then
-                line+="   ${fetch[entry]}"
-                ((entry++))
-            fi
-            printf "%s\r\n" "$line"
-        done < $path/$frame
-    
-        sleep $delay
-    done
-done
+	if [ -n "${username}" ] & [ -n "${hostname}" ]; then
+		info+=("${h1}${username}${c0}@${h1}${hostname}${c0}")
+	fi
+
+	if [ -n "${os}" ]; then
+		info+=("${h1}os${c0}     ${os}")
+	fi
+
+	if [ -n "${kernel}" ]; then
+		info+=("${h1}kernel${c0} ${kernel}")
+	fi
+
+	if [ -n "${shell}" ]; then
+		info+=("${h1}shell${c0}  ${shell}")
+	fi
+
+	if [ -n "${uptime}" ]; then
+		info+=("${h1}uptime${c0} ${uptime}")
+	fi
+
+	info_length=${#info[@]}
+}
+
+onexit () {
+	clear
+	echo -e "\e[?25h"
+}
+
+oninit() {
+	trap onexit EXIT
+	trap clear SIGWINCH
+	echo -e "\e[?25l"
+	clear
+}
+
+draw() {
+	echo -en "\e[H"
+	i=0
+	while IFS= read -r line; do
+		line=$(echo "${line}" | sed "s/{c1}/${c1}/g;s/{c0}/${c0}/g")
+		if [ ${i} -lt ${info_length} ]; then
+			line+=${info[i]}
+			((i++))
+		fi
+		echo "${line}"
+	done < $1
+
+	sleep $delay
+}
+
+loop() {
+	while true; do
+		for frame in $(ls $path | sort -g); do
+			draw ${path}/${frame}
+		done
+	done
+}
+
+main() {
+	input $@
+	check
+	fetch
+	oninit
+	loop
+}
+
+
+main $@
 
